version: '3'

services:
  
  bot:
    build: .
    command: python bot.py
    container_name: bot_telegram
    restart: always
    env_file:
      - variables.env
    links:
      - mongodb:mongo
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo_jampp
    volumes:
      - ./data/db:/data/db